### ISSUE TITLE
Replace All Peds with Zombies?

### ISSUE THREAD

**Issue by Duderocktv** [Dislaik/esx_zombiesystem#2]
More of a feature request.
Your system works awesome!

Is there a way you could replace all citizens around the map without running higher than the already high 2.0MS in resmon?

**Comment by Dislaik** [comment]
Apparently the file loot.lua is the causing, i will try optimize this
without loot.lua you should have 0.30 ms prox

**Comment by Dislaik** [comment]
loot.lua causing +0.30 MS, change Config.ObjectDropLoot to false or set a low amount entities in Config.ObjectsLoot
